// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn1_TfbYsiVf7OjEWd3CDlcU1BwNYqy2U',
    appId: '1:193732199061:web:b4c3de896f5aa75045119c',
    messagingSenderId: '193732199061',
    projectId: 'firelearn-7b6a7',
    authDomain: 'firelearn-7b6a7.firebaseapp.com',
    storageBucket: 'firelearn-7b6a7.appspot.com',
    measurementId: 'G-R7TV59YB4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL3ngpFkHZjQiqlC_v5pVXiGyCIRc7cko',
    appId: '1:193732199061:android:e024adc2f62d7cc045119c',
    messagingSenderId: '193732199061',
    projectId: 'firelearn-7b6a7',
    storageBucket: 'firelearn-7b6a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdh77WeSSV4hYZlt2qkrq1oGtjDCFi-sY',
    appId: '1:193732199061:ios:ea924ce2bf5a8fcd45119c',
    messagingSenderId: '193732199061',
    projectId: 'firelearn-7b6a7',
    storageBucket: 'firelearn-7b6a7.appspot.com',
    iosBundleId: 'com.example.firelearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdh77WeSSV4hYZlt2qkrq1oGtjDCFi-sY',
    appId: '1:193732199061:ios:ea924ce2bf5a8fcd45119c',
    messagingSenderId: '193732199061',
    projectId: 'firelearn-7b6a7',
    storageBucket: 'firelearn-7b6a7.appspot.com',
    iosBundleId: 'com.example.firelearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn1_TfbYsiVf7OjEWd3CDlcU1BwNYqy2U',
    appId: '1:193732199061:web:11f93689ca73007945119c',
    messagingSenderId: '193732199061',
    projectId: 'firelearn-7b6a7',
    authDomain: 'firelearn-7b6a7.firebaseapp.com',
    storageBucket: 'firelearn-7b6a7.appspot.com',
    measurementId: 'G-KCXH5H2QEP',
  );
}
